service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  
  stage: dev
  region: eu-west-1

  environment:
    SNS_TOPIC_ARN: { Ref: SNSTopic }

  iamRoleStatements:
    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        - Fn::GetAtt: [ SQSQueue, Arn ]
    - Effect: "Allow"
      Action: "sns:*"
      Resource:
        Ref: SNSTopic

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: "pikagrigoriy@gmail.com"
        Protocol: "email"
        TopicArn:
          Ref: SNSTopic

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  getProductsList:
    handler: ./handlers/getProductsList.getProductsList
    events:
      - http:
          path: /products
          method: get
          cors: true
  addProduct:
    handler: ./handlers/addProduct.addProduct
    events:
      - http:
          path: /products
          method: post
          cors: true
  
  getProductById:
    handler: ./handlers/getProductById.getProductById
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true

  catalogBatchProcess:
    handler: ./handlers/catalogBatchProcess.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - SQSQueue
              - Arn