service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  
  stage: dev
  region: eu-west-1
  
  environment:
    # NODE_TLS_REJECT_UNAUTHORIZED: 0

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  getProductsList:
    handler: ./handlers/getProductsList.getProductsList
    events:
      - http:
          path: /products
          method: get
          cors: true 
  
  getProductById:
    handler: ./handlers/getProductById.getProductById
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true 

