service: import-service

provider:
  name: aws
  runtime: nodejs16.x
  
  stage: dev
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::s3-serverless-integration"
    - Effect: "Allow"
      Action: 
        - "s3:*"
      Resource:
        - "arn:aws:s3:::s3-serverless-integration/*"

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true


functions:
  imageUpload:
    handler: ./handlers/importFileParser.importFileParser
    events:
      - s3:
          bucket: s3-serverless-integration
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
          forceDeploy: true

  importProductsFile:
    handler: ./handlers/importProductsFile.importProductsFile
    events:
      - http:
          path: /import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
